### ISSUE TITLE
Feature Request: Open and save to .highland files

### ISSUE THREAD

**Issue by tyang209** [piersdeseilligny/betterfountain#102]
This is a real pie-in-the-sky feature here but it would be really great to be able to open and modify .highland files. I personally work back and forth between a PC and a Macbook so it would be great to have a native windows way to edit a script without juggling multiple files.

If this is out of scope for the extension do you have any idea if there are any other extensions that can open and deal with textbundles?

**Comment by piersdeseilligny** [comment]
@tyang209 I'd really love to implement this too! However this is only _sort of_ possible, because the vscode API doesn't really have a sensible way of editing/saving binary files. The closest thing is the read-only ["Virtual Document"](https://code.visualstudio.com/api/extension-guides/virtual-documents), but even then it wouldn't support opening files directly, only through a command. And it wouldn't be possible to edit/save the document anyway.

I think the best option, currently, would be to use a [FileSystemProvider](https://code.visualstudio.com/api/references/vscode-api#FileSystemProvider), which would allow saving/editing documents, but even then it would have to go through a command (right-click on .highland file > "Open as Fountain", or something along those lines). And would be very janky in general. If Microsoft were to resolve [this issue](https://github.com/microsoft/vscode/issues/106916), then it'd be possible, even easy, to support editing .highland files.

Not all is bleak though, as I'm currently developing (albeit slowly) a standalone version of BetterFountain, which wouldn't be limited by vscode's API. Real .highland support is one of the reasons I'm working on this actually (you can see dev updates/discussion on the [Discord server](https://discord.gg/QBm7tKQ)). For the moment though, I don't think there's any better option than renaming `.highland` to `.zip`, extracting it, editing the text.fountain file, and rearchiving it to a .highland file :/

**Comment by tyang209** [comment]
@piersdeseilligny  That makes sense. Thank you so much for your thoughtful response. I'll definitely keep an eye on both that VS Code issue and your standalone version. 

Thank you again! I'll close this issue.
