### ISSUE TITLE
Action line max characters. Get's ignored.

### ISSUE THREAD

**Issue by kauderk** [piersdeseilligny/betterfountain#110]
At the time I'm trying to reduce the word count or wrapping the text with 

`"[fountain]": {
        "editor.wordWrap": "on", "editor.wordWrapColumn": 50 
    }`

But nothing happens. Because It's esencial to know when an actual line (that will be printed) contents.  

Also. How do I change the preview window background color to black?

**Comment by daryluren** [comment]
Hi @KauDerK 

This is how I like mine
```
    "[fountain]": {
        "editor.wordWrapColumn": 57,
        "editor.wordWrap": "wordWrapColumn",
        "editor.rulers": [57]
    }, 
...
    "fountain.general.previewTheme": "vscode",
...
```

What you want is "editor.wordWrap": "wordWrapColumn" so that the wordwrap is based on the other "editor.wordWrapColumn" setting, not simply turning wordwrap on and off in general. If you want it to wrap at the same column as the pdf, use 57.

(I like having a ruler displayed at the same column so I can see where it will wordwrap which helps when I resize my windows.)

The last setting in my sample is the setting to make the preview theme match the vscode theme, meaning it will be black when you use a dark theme.

**Comment by piersdeseilligny** [comment]
Thanks @daryluren ! Did that solve your issue @KauDerK ?

**Comment by kauderk** [comment]
I just saw the response. It is very well explained. I'll give it a try.
Thanks.
