### ISSUE TITLE
Just a quick question and suggestion

### ISSUE THREAD

**Issue by jaxbeeradil** [piersdeseilligny/betterfountain#143]
For the preview tool, how do you toggle dark mode? And a suggestion is a synopsis outline tool for scene headers and scene numbers in preview mode

**Comment by piersdeseilligny** [comment]
Hi @jaxbeeradil ! If you change the preview theme to "vscode" rather than "paper" in the settings:

![image](https://user-images.githubusercontent.com/42496508/134419209-e36239d7-c4b1-4bc2-8759-3bf46ef1d19f.png)

The preview will adopt the color theme of vscode (and if it is dark, it will therefore be dark in the preview).

For the synopsis outline and scene numbers in the preview, these can also be enabled in the settings:

![image](https://user-images.githubusercontent.com/42496508/134419713-76373e0b-eb3e-4b6b-af7a-cf1b153df1cf.png)
![image](https://user-images.githubusercontent.com/42496508/134419748-193519cb-4645-4b4c-9627-aef08343e18c.png)
