### ISSUE TITLE
Allow .txt file extension

### ISSUE THREAD

**Issue by stephenberry** [piersdeseilligny/betterfountain#145]
Thanks so much for your work on this fantastic extension.

Is there a way for the user to allow Better Fountain to work on .txt files? I'd like to be able to open my files with a basic text editor in contexts where Visual Code isn't available.

Thanks!

**Comment by thegreentimtam** [comment]
Sorry to jump in, but what text editor can't work with fountain files? Most basic text editors I've used (including Notepad, TextEdit, even Nano) can open any file you want.

**Comment by piersdeseilligny** [comment]
hi @stephenberry  - what exactly do you mean? Do you mean opening fountain files with BetterFountain but without vscode?

**Comment by stephenberry** [comment]
@piersdeseilligny I just mean that if I open a file with a `.txt` extension in VSCode BetterFountain won't recognize or parse it, and I'd like the option to tell BetterFountain to work with this extension.

@thegreentimtam All the desktop text editors I've used handle `.fountain` just fine. But, I found multiple IOS text editors won't open a `.fountain` file. For example, Pages can open a `.txt` file on IOS but not a `.fountain`.

**Comment by piersdeseilligny** [comment]
Ahh right, so it turns out this is already possible :) You just need to tell vscode that the content of the document is fountain:

![image](https://user-images.githubusercontent.com/42496508/140804653-96c620c6-20e9-4d46-8204-eb93b0b3e5b2.png)
![image](https://user-images.githubusercontent.com/42496508/140804707-e3f2ec81-910d-4633-99d5-31f59cefe1ce.png)

This should work, but let me know if you run into any issues

**Comment by stephenberry** [comment]
Fantastic, that works great! Thanks
