### ISSUE TITLE
Notes are treated as 'Action' in duration measurement

### ISSUE THREAD

**Issue by double-u-a** [piersdeseilligny/betterfountain#158]
Usually put a big bunch of notes at the beginning of a script but noticed it was being treated as 'Action' in the duration measurements, making me think I had written more script than I thought 😅 

<img width="1145" alt="Screenshot 2022-03-06 at 02 39 08" src="https://user-images.githubusercontent.com/7398973/156906852-f76902d7-56c3-4d8e-b0f8-dd97f5a9dc1f.png">

**Comment by piersdeseilligny** [comment]
Thanks for reporting this! Unfortunately BetterFountain isn't currently compatible with notes that contain carriage returns (they have to be contained within one line). It's far from ideal, but this is because of the parser's internal architecture which would make it kinda messy.

That said, this bug is still relevant: notes seem to be excluded correctly if they're within a scene, but not when they're by themselves. I'm going to investigate and hopefully publish an update fairly soon which fixes this (and also which disables syntax highlighting of notes if they contain line breaks - it's confusing).

**Comment by double-u-a** [comment]
Ah I understand! Glad to stumble on a bug :) 

My workaround is to just boneyard the opening notes to avoid stats detection and un-boneyard them on PDF export so they show up

**Comment by piersdeseilligny** [comment]
That's it fixed in version 1.10.0, which should be live in the marketplace now! I've also removed syntax highlighting for notes that contain a line break, so it should be a little more obvious now :)
