### ISSUE TITLE
Feature request: Smart quotes

### ISSUE THREAD

**Issue by leoleoimn** [piersdeseilligny/betterfountain#173]
Is it possible to have straight quotes (like "…" and '…') be parsed as curly (or slanted) quotes (“…” or ‘…’) in the output? This would apply to apostrophes as well (Jake's → Jake’s)

For example, if the input is:
![Screenshot 2022-07-18 135436](https://user-images.githubusercontent.com/71240029/179453108-25137399-2be9-40c6-a336-eb955956c6c6.png)

Then it would output:
![image](https://user-images.githubusercontent.com/71240029/179452917-12b5a211-bfaa-4558-8202-919451bcb1f8.png)

**Comment by furrykef** [comment]
[The Fountain spec](https://fountain.io/syntax) says the omission of this feature is intentional: "Fountain doesn't do any of that, because the screenplay typographical convention is to emulate a typewriter. However you type your apostrophes, quotes, dashes, and dots, that's how they'll wind up in the screenplay." But, on the other hand, that means you can still use curly quotes if you type them yourself. (A Compose key is very handy for this; if you use Windows, try WinCompose.)

Smart quotes can also be annoying to deal with when the feature gets it wrong, such as producing " ‘cause" instead of " ’cause" for the common contraction of "because". That problem goes away when you type them yourself.
