### ISSUE TITLE
Support for non-latin character languages such as Chinese, Hebrew or Arabic

### ISSUE THREAD

**Issue by rubenxyz** [piersdeseilligny/betterfountain#178]
Hello Betterfountain family, 
I am writing a screenplay that is both in English and Hebrew. 
Tried to export some Hebrew text but the characters didn't show up in the outputted PDF. 
Would it be possible to make Betterfountain support languages that don't use latin characters or does it rely on some third-party PDF-module that can't handle it?
Best, 
Ruben

**Comment by piersdeseilligny** [comment]
Hi @rubenxyz, thanks for reporting this! Unfortunately the PDF Library that BetterFountain uses doesn't support fallback fonts, which means the only way to get this working correctly is to use a font which supports both English and Hebrew characters.

The issue is tracked here: https://github.com/piersdeseilligny/betterfountain/issues/133

Hope this helps!

**Comment by rubenxyz** [comment]
Thank you @piersdeseilligny!
I used Adobe Hebrew font to solve the issue and it work. Going to try and find a more Courier Prime-like font. Perhaps even contribute to the Courier Prime project with a set of Hebrew characters.

**Comment by rubenxyz** [comment]
PS. 
The Fountain parser couldn't handle Hebrew characters, I tried adding @ as a power user but couldn't get it to work. It does work if the name of the person speaking is written in latin characters like this: 

```
RUBEN
אני מאוד אוהב אנשים שמייצרים כלים לתחביר המזרקה
```
