### ISSUE TITLE
Q: How to change syntax colors ?

### ISSUE THREAD

**Issue by X-Raym** [piersdeseilligny/betterfountain#210]
Hi,

I come from another fountain system (Atom based) which had slightly different color

Changing the whole VS code theme is a bit much as it will impatc other language I use and all UI elements,

just need to change color of character lines and name, things like that

How can I do it ?

Thx !

**Comment by piersdeseilligny** [comment]
Hi @X-Raym !

So in order to only change the colours of fountain elements, you can customise any theme in your settings.json file, targeted specifically to fountain syntax, using the following guide: https://dev.to/psudo-dev/how-to-customize-or-make-your-own-vscode-color-theme-49j1

If you inspect a fountain document using the "Developer: Inspect Editor Tokens and Scopes"

It should all be fairly straightforward - Hopefully this helps!

All the best,
Piers

**Comment by X-Raym** [comment]
Thanks you for the assistance ! Cheers, and thx again for this extension ! 🙏

Le 18 févr. 2024, 16:14, à 16:14, Piers Deseilligny ***@***.***> a écrit:
