### ISSUE TITLE
Unable to properly format Malayalam language

### ISSUE THREAD

**Issue by Amal717** [piersdeseilligny/betterfountain#216]
I am not able to convert Malayalam utf-8 encoded language scripts to pdf. The text appears like gibberish

**Comment by piersdeseilligny** [comment]
Hi, thanks for creating this issue. The problem is actually that pdfkit (the PDF Library BetterFountain uses) does not support fallback fonts. It's an issue that's plagued the library [for the past 10 years][https://github.com/foliojs/pdfkit/issues/201], but there's still no real solution to it...

The alternative is to use a font which supports Malayalam characters, which you can do by adding the Font: title page key.
