### ISSUE TITLE
Character names in not English aren't recognized

### ISSUE THREAD

**Issue by avega** [piersdeseilligny/betterfountain#24]
If character name written in not english alphabet, for example - in russian, then it's not recognized. As well the following dialogue.

**Comment by piersdeseilligny** [comment]
I'm going to look at implementing this, but it would require completely redesigning the regex expressions that currently serve for syntax highlighting and tokenization to use unicode ranges. I also want to make sure the performance difference would be at worst negligeable.

In the meantime, you can force character names by preceding them with `@`. For example, instead of `АДРИАН`, use `@АДРИАН`

**Comment by piersdeseilligny** [comment]
Turns out this was way easier to fix than I expected. Fixed in 1.2.2, which is currently live in the marketplace.

**Comment by avega** [comment]
Thank you! That was fast! :)
