### ISSUE TITLE
Broken Russian alphabet in exported PDF file

### ISSUE THREAD

**Issue by avega** [piersdeseilligny/betterfountain#25]
In preview window Russian alphabet is shown correctly, but in exported PDF file it's looks like this:

BtBCâÔBCâ =CR BC : D  4C„0C ́>C40CÄ8... Aä=C‚ :
D >Cd0C ́5CÔ8Dâ @C ACô>Ct=C ND$ADò BCä;DÄ:Câ =C 
C =C4;C„9D :Cä< Dô7D ́:CRâ  D 0C$4C  O CÔ0Cô8D 0C°
D 0Ct@C 1CäBDt8C¤C Câ 4C =CÔ>C’ ?D >C ;CT<CRà
B$0C¢ÔGD$> C CCD5CÂ 6CD0D$L.

**Comment by piersdeseilligny** [comment]
This is a font-related issue, as I can fix it by forcing pdfkit to render with a font that supports Cyrillic characters (like DejaVu Sans).

I'm currently working on 1.3.0 which will add support for custom fonts and significantly improve autocomplete. To fix this bug I'il also change the default font to one which supports non-latin alphabets.

**Comment by avega** [comment]
Yes, I think custom fonts will be solution (if user will be able to change it in settings). Because it's not easy to find suitable cyrillic monospace font.
"Courier New" font is lite but it's supports cyrillic characters and may be other locales.

**Comment by piersdeseilligny** [comment]
I'm busy changing the default font to Courier Prime, as it looks a lot nicer and supports cyrillic characters. It will be possible to change the font used in a fountain document with a `Font:` title page key (I'm not adding anything to the settings, as they're kind of a mess and pretty unintuitive)

**Comment by avega** [comment]
I've installed Courier Prime and it's not support Cyrillic characters (official version), but there is modified one that supports.
So, if I get it right: editor font will be in VS Code settings, preview and PDF export - in title page key?

**Comment by piersdeseilligny** [comment]
@avega Yes, that's it. Maybe I will also add an option to change the default font in the vscode settings, but I'm not sure yet.

About Courier Prime, I should have specified I'm using a version called [Courier Prime Cyrillic](http://dimkanovikov.pro/courierprime/) which includes cyrillic characters in addition to Latin ones.

**Comment by piersdeseilligny** [comment]
So it turns out there's going to be a problem in supporting custom fonts. I've got everything working perfectly in the live preview (it's all live, and even shows a warning in the editor if the font is unavailable). However the library to generate PDFs (`pdfkit`) doesn't support accessing system fonts. So if you define for example "Courier Final Draft" as a font, `pdfkit` won't know where to look for the `.ttf` files associated with the font, even if it's installed on the system.

So I'm going to disable this feature for the moment, and just switch both the live preview and the pdf renderer to using Courier Prime, which is embedded into the extension. It's nicer and supports more characters than the current default (Courier).

EDIT: Ok so actually it was easier than I thought, it's part of 1.3.0
