### ISSUE TITLE
No Proper Spacing After Dual Dialogue When Exported to PDF

### ISSUE THREAD

**Issue by misterjules** [piersdeseilligny/betterfountain#30]
Didn't know if I could leave this space blank...

Other than this issue, just wanted to say thanks.

**Comment by osomfinch** [comment]
This issue is still there. 
![Screenshot from 2020-06-10 15-52-20](https://user-images.githubusercontent.com/25690983/84269962-a1d49700-ab32-11ea-87e6-37fb6a74c4fb.png)

In the live preview everything is fine. The problem appears only when you export to PDF.

Otherwise, thank you for the great work.

**Comment by piersdeseilligny** [comment]
@osomfinch Apologies for taking so long to fix this! It will be fixed by the next version (1.6.0) which I should be releasing soon
