### ISSUE TITLE
Synopsis text is counted in running time estimate

### ISSUE THREAD

**Issue by chipotle** [piersdeseilligny/betterfountain#34]
I noticed that a screenplay that I'm working on that's only on page 8 shows a 32:27 minute running time -- it appears that Better Fountain is counting all the synopsis lines that begin with `= ` as if they're action descriptions and thus affect the running time. I don't know whether it's also counting the Markdown-esque section lines. (Yes, I have about a 4000-word outline here...)

**Comment by piersdeseilligny** [comment]
Currently, yes, Better Fountain does indeed use the length of the entire document to calculate the estimate (including synopsis text, title page, etc...). It's funny you should raise this issue now, because literally yesterday I started working on a fix.

I just need to figure out the correct multipliers to convert the character count of dialogue and the character count of action elements to the running time estimate, but this will definitely be fixed in the next version.

**Comment by piersdeseilligny** [comment]
@chipotle this has been fixed in 1.4.0, which is now live in the marketplace
