### ISSUE TITLE
export pdf creates filename.pdf..pdf output

### ISSUE THREAD

**Issue by MarkAins** [piersdeseilligny/betterfountain#4]
Running on mac High Seirra, latest VSC. when I go to export a pdf I get an file output box and it has prefilled the filename with filename.pdf..pdf (which I think is a bit daft). If I edit the filename to end with .pdf I get an error message 

You cannot save this document with extension “.pdf” at the end of the name. The required extension is “..pdf”.

Is this the correct behaviour? If so, what is the reasoning. Normally I just want to export a file with a .pdf extension.

**Comment by Quinncuatro** [comment]
I don't have a laptop in front of me, but I've looked at the code for that
myself. I think it's an error with the way the afterwriting dependency is
implemented here. I think the maintainer linked to the relevant line is
issue #2?

I'll take another look tomorrow.

**Comment by piersdeseilligny** [comment]
This had to do with slightly odd behaviour related to the way the save dialog behaves in regards to filtering file names on different operating systems. It has been fixed for version 1.1.2, however the "export to PDF" feature may still not work on mac os, because of oddities related to npm. I'm currently looking at fixing this.
