### ISSUE TITLE
boneyard items display in live preview

### ISSUE THREAD

**Issue by asterox** [piersdeseilligny/betterfountain#6]
Text wrapped in boneyard tags (/*..........*/) still display in the live preview.

**Comment by piersdeseilligny** [comment]
This issue (and many others) are fixed in the `feature/newparser` branch as of commit 599758bc94fe9fc1e9e4e52bffd6c98b136f02d5, which involved completely replacing the fountain parser used previously (based on fountain-js) with a quite heavily modified version of the one in afterwriting.

I've yet to integrate the export to pdf functionality, but once that's done the `feature/newparser` branch can be merged into `master`, and that will be a new release, fixing this in addition to the even more problematic issue #2.
